# Generated by Django 4.1.7 on 2023-11-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_type', models.CharField(choices=[('compliant', 'Compliant'), ('partially-compliant', 'Partially Compliant'), ('non-compliant', 'Non-Compliant')], max_length=20)),
                ('audit_observations', models.TextField()),
                ('recommandations', models.TextField()),
            ],
        ),
    ]
