# Generated by Django 4.1.7 on 2023-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_auto', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
