# Generated by Django 4.1.7 on 2023-11-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_auto', '0005_userresponse_summary_userresponse_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='title',
        ),
    ]
