# Generated by Django 4.1.7 on 2023-11-21 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp_auto', '0006_remove_userresponse_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoreResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('summary', models.TextField()),
                ('compliance_type', models.CharField(choices=[('compliant', 'Compliant'), ('partially-compliant', 'Partially Compliant'), ('non-compliant', 'Non-Compliant')], max_length=20)),
                ('audit_observations', models.TextField()),
                ('recommandations', models.TextField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
