# Generated by Django 4.1.7 on 2024-03-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp_auto', '0009_alter_addmoreresponse_compliance_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_point_summaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_point_text', models.TextField()),
                ('summary', models.TextField(max_length=255)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
