# Generated by Django 4.1.7 on 2024-03-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp_auto', '0010_audit_point_summaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='audit_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comp_auto.audit_point_summaries'),
        ),
    ]
